# Project: SiHiDa
# Makefile created by Dev-C++ 5.8.2

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = Procedures.o SiHiDamain.o Objects.o
LINKOBJ  = Procedures.o SiHiDamain.o Objects.o
LIBS     = -L"D:/Programming/Dev-Cpp/MinGW64/lib32" -L"D:/Programming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -g3
INCS     = -I"D:/Programming/Dev-Cpp/MinGW64/include" -I"D:/Programming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Programming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/Programming/Dev-Cpp/MinGW64/include" -I"D:/Programming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Programming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/Programming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = SiHiDa.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Procedures.o: Procedures.cpp
	$(CPP) -c Procedures.cpp -o Procedures.o $(CXXFLAGS)

SiHiDamain.o: SiHiDamain.cpp
	$(CPP) -c SiHiDamain.cpp -o SiHiDamain.o $(CXXFLAGS)

Objects.o: Objects.cpp
	$(CPP) -c Objects.cpp -o Objects.o $(CXXFLAGS)
